In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
# npz 파일 중 i_data 불러오기

Welding_data = np.load('E:/3.08/MTF/MTF.npz')

i_data = Welding_data['i_data']

Welding_data.close()

In [3]:
# i_data csv save

np.savetxt('E:/3.08/MTF/i_data/i_data_10.csv', i_data, fmt='%s', header='i_data')

In [4]:
# index = i_data

i_data = pd.read_csv('E:/3.08/MTF/i_data/i_data_10.csv')
i_data = np.array(i_data)
i_data = i_data.reshape(len(i_data),)
print(i_data.shape)

(1800,)


In [5]:
print(i_data)

['H_237' 'N_33' 'P_217' ... 'P_162' 'N_77' 'H_69']


In [6]:
# i_data_list : i_data의 순서
i_data_list = []

for i in range(len(i_data)):
    i_data_list.append(i)

In [7]:
# key : i_data_list
# value : i_data

diction_i_data = dict(zip(i_data_list, i_data))

for key, element in diction_i_data.items():
    print("{} = {}".format(key, element))

0 = H_237
1 = N_33
2 = P_217
3 = N_329
4 = P_269
5 = P_146
6 = P_265
7 = P_599
8 = H_167
9 = N_240
10 = N_454
11 = P_183
12 = N_473
13 = H_121
14 = P_57
15 = P_225
16 = H_402
17 = H_531
18 = P_134
19 = P_279
20 = H_206
21 = N_210
22 = H_337
23 = N_280
24 = N_550
25 = N_564
26 = P_348
27 = H_196
28 = P_20
29 = H_525
30 = H_321
31 = P_18
32 = P_223
33 = N_170
34 = H_215
35 = H_403
36 = N_51
37 = N_406
38 = H_53
39 = H_25
40 = H_406
41 = P_54
42 = P_187
43 = H_138
44 = H_370
45 = N_74
46 = N_46
47 = P_219
48 = N_140
49 = N_213
50 = N_125
51 = H_554
52 = P_50
53 = H_484
54 = H_549
55 = P_24
56 = N_344
57 = N_134
58 = N_560
59 = N_289
60 = P_276
61 = H_542
62 = P_209
63 = N_224
64 = P_252
65 = N_448
66 = H_460
67 = P_429
68 = P_506
69 = H_11
70 = N_196
71 = H_207
72 = H_34
73 = H_523
74 = N_497
75 = H_495
76 = H_126
77 = P_179
78 = H_191
79 = P_76
80 = H_323
81 = P_392
82 = H_307
83 = N_443
84 = N_97
85 = N_220
86 = P_412
87 = H_412
88 = H_502
89 = H_363
90 = N_283
91 = P_508
92 = P_70
93 =

In [8]:
# train_data.csv 불러오기

# trainset = train

trainset = pd.read_csv('E:/3.08/MTF/train/train_10.csv')
trainset = np.array(trainset)
trainset = trainset.reshape(len(trainset),)
print(trainset.shape)
print(trainset)

(1295,)
[1.000e+00 2.000e+00 3.000e+00 ... 1.437e+03 1.438e+03 1.439e+03]


In [9]:
# diction_i_data의 value값을 train_list에 저장

train_list = []

for i in range(0,len(trainset)):
    train_list.append(diction_i_data.get(trainset[i]))
    print(diction_i_data.get(trainset[i]))

N_33
P_217
N_329
P_269
P_146
P_265
H_167
N_240
N_454
P_183
N_473
H_121
P_225
H_402
H_531
P_134
P_279
H_206
N_210
H_337
N_280
N_564
P_348
H_196
P_20
H_525
H_321
P_18
P_223
N_170
H_215
H_403
N_51
N_406
H_53
H_25
H_406
P_54
P_187
H_138
H_370
N_46
P_219
N_140
N_213
N_125
H_554
P_50
H_484
H_549
P_24
N_134
N_560
N_289
P_276
H_542
P_209
N_224
P_252
N_448
H_460
P_429
P_506
H_11
N_196
H_207
H_34
H_523
N_497
H_495
H_126
P_179
H_191
P_76
H_323
P_392
P_412
H_412
H_502
H_363
N_283
P_508
P_70
N_413
N_0
P_89
P_323
N_476
P_447
H_595
H_346
H_287
H_311
N_528
N_440
P_197
N_447
P_399
P_292
P_282
P_6
N_109
H_442
N_548
H_488
P_488
P_418
H_474
N_182
P_119
P_17
P_258
P_141
N_95
H_52
N_290
H_97
N_261
H_118
H_434
N_203
N_199
N_367
N_147
P_211
H_255
N_255
P_298
N_572
P_1
N_392
N_274
H_203
P_118
H_1
H_185
P_62
H_168
H_44
N_192
P_77
N_244
N_273
H_272
H_283
N_150
H_534
H_112
P_546
N_284
N_351
N_532
P_571
P_494
P_120
H_62
H_300
P_388
P_308
N_24
H_459
H_447
P_330
H_477
P_168
P_479
N_187
N_534
N_165
P_218
H_111
P_115


In [10]:
# train_list.csv로 저장
np.savetxt('E:/3.08/MTF/train_list/train_list_10.csv', train_list, fmt="%s", header='train_list')

In [11]:
# Image dictionary

# Image index 생성

index_length = int(len(i_data)/3)
print(index_length)

# Humping index
list_Humping_index = []
for i in range(index_length):
    list_Humping_index.append('H_' + str(i))

# Normal index
list_Normal_index = []
for j in range(index_length):
    list_Normal_index.append('N_'+str(j))

# Porosity index
list_Porosity_index = []
for k in range(index_length):
    list_Porosity_index.append('P_'+str(k))

Humping_index = np.array(list_Humping_index)
Normal_index = np.array(list_Normal_index)
Porosity_index = np.array(list_Porosity_index)

600


In [12]:
# N,H,P index concatenate

Merge_index = np.concatenate((Humping_index, Normal_index, Porosity_index), axis=0)

print(Merge_index.shape)

(1800,)


In [13]:
# Merge_index.csv 저장
np.savetxt('E:/3.08/MTF/Merge_index/Merge_index_10.csv', Merge_index, fmt="%s")

In [14]:
# Image import

from PIL import Image

list_Merge_Humping = []
list_Merge_Normal = []
list_Merge_Porosity = []

for i in range(0,len(list_Normal_index)):
    M_H = Image.open('E:/3.08/MTF/Image/Merge_Humping/' + f'H_{i}.tiff')
    M_N = Image.open('E:/3.08/MTF/Image/Merge_Normal/' + f'N_{i}.tiff')
    M_P = Image.open('E:/3.08/MTF/Image/Merge_Porosity/' + f'P_{i}.tiff')

    M_H = np.array(M_H)
    M_H = M_H.reshape(200,200,2)

    M_N = np.array(M_N)
    M_N = M_N.reshape(200,200,2)

    M_P = np.array(M_P)
    M_P = M_P.reshape(200,200,2)

    list_Merge_Humping.append(M_H)
    list_Merge_Normal.append(M_N)
    list_Merge_Porosity.append(M_P)

In [15]:
M_H = np.array(list_Merge_Humping)
M_N = np.array(list_Merge_Normal)
M_P = np.array(list_Merge_Porosity)

In [16]:
# Image list concatenate

Merge_image = np.concatenate((M_H,M_N,M_P), axis=0)

print(Merge_image.shape)

(1800, 200, 200, 2)


In [17]:
# key : Merge_index
# value : Merge_image

diction_image = dict(zip(Merge_index, Merge_image))

In [18]:
for key,element in diction_image.items():
    print("{} = {}".format(key,element))

H_0 = [[[112 112]
  [112 112]
  [  0   0]
  ...
  [  0   0]
  [  0   0]
  [  0   0]]

 [[132 132]
  [ 10  10]
  [ 20  20]
  ...
  [ 20  20]
  [ 20  20]
  [ 20  20]]

 [[  0   0]
  [  0   0]
  [127 127]
  ...
  [127 127]
  [127 127]
  [127 127]]

 ...

 [[  0   0]
  [  0   0]
  [127 127]
  ...
  [127 127]
  [127 127]
  [127 127]]

 [[  0   0]
  [  0   0]
  [127 127]
  ...
  [127 127]
  [127 127]
  [127 127]]

 [[  0   0]
  [  0   0]
  [127 127]
  ...
  [127 127]
  [127 127]
  [127 127]]]
H_1 = [[[ 81  81]
  [ 71  71]
  [ 20  20]
  ...
  [  0   0]
  [ 71  71]
  [ 71  71]]

 [[ 63  63]
  [ 63  63]
  [ 95  95]
  ...
  [  0   0]
  [ 63  63]
  [ 63  63]]

 [[ 30  30]
  [ 30  30]
  [ 40  40]
  ...
  [122 122]
  [ 30  30]
  [ 30  30]]

 ...

 [[  0   0]
  [ 30  30]
  [ 91  91]
  ...
  [132 132]
  [ 30  30]
  [ 30  30]]

 [[ 63  63]
  [ 63  63]
  [ 95  95]
  ...
  [  0   0]
  [ 63  63]
  [ 63  63]]

 [[ 63  63]
  [ 63  63]
  [ 95  95]
  ...
  [  0   0]
  [ 63  63]
  [ 63  63]]]
H_2 = [[[ 71  71

In [19]:
# diction_image key에 diction_i_data value 넣어서 학습에 사용 된 이미지만 따로 저장


train_image_list = []

for i in range(len(train_list)):
    train_image_list.append(diction_image.get(train_list[i]))

In [20]:
train_image = np.array(train_image_list)
print(train_image.shape)

(1295, 200, 200, 2)


In [21]:
for i in range(len(train_list)):
    print(train_list[i])

N_33
P_217
N_329
P_269
P_146
P_265
H_167
N_240
N_454
P_183
N_473
H_121
P_225
H_402
H_531
P_134
P_279
H_206
N_210
H_337
N_280
N_564
P_348
H_196
P_20
H_525
H_321
P_18
P_223
N_170
H_215
H_403
N_51
N_406
H_53
H_25
H_406
P_54
P_187
H_138
H_370
N_46
P_219
N_140
N_213
N_125
H_554
P_50
H_484
H_549
P_24
N_134
N_560
N_289
P_276
H_542
P_209
N_224
P_252
N_448
H_460
P_429
P_506
H_11
N_196
H_207
H_34
H_523
N_497
H_495
H_126
P_179
H_191
P_76
H_323
P_392
P_412
H_412
H_502
H_363
N_283
P_508
P_70
N_413
N_0
P_89
P_323
N_476
P_447
H_595
H_346
H_287
H_311
N_528
N_440
P_197
N_447
P_399
P_292
P_282
P_6
N_109
H_442
N_548
H_488
P_488
P_418
H_474
N_182
P_119
P_17
P_258
P_141
N_95
H_52
N_290
H_97
N_261
H_118
H_434
N_203
N_199
N_367
N_147
P_211
H_255
N_255
P_298
N_572
P_1
N_392
N_274
H_203
P_118
H_1
H_185
P_62
H_168
H_44
N_192
P_77
N_244
N_273
H_272
H_283
N_150
H_534
H_112
P_546
N_284
N_351
N_532
P_571
P_494
P_120
H_62
H_300
P_388
P_308
N_24
H_459
H_447
P_330
H_477
P_168
P_479
N_187
N_534
N_165
P_218
H_111
P_115


In [22]:
# train_image folder 생성
os.mkdir('E:/3.08/MTF/train_image' + '/' + 'train_10')

In [23]:
for i in range(len(train_image)):
    image_save = Image.fromarray((train_image[i]*255).astype(np.uint8))
    file_name = train_list[i]
    print(file_name)
    image_save.save('E:/3.08/MTF/train_image/train_10/'+f'{i}_{file_name}.tiff')
    #f'{trainset}_{file_name}.tiff' 로 출력될 수 있게 끔 수정

N_33
P_217
N_329
P_269
P_146
P_265
H_167
N_240
N_454
P_183
N_473
H_121
P_225
H_402
H_531
P_134
P_279
H_206
N_210
H_337
N_280
N_564
P_348
H_196
P_20
H_525
H_321
P_18
P_223
N_170
H_215
H_403
N_51
N_406
H_53
H_25
H_406
P_54
P_187
H_138
H_370
N_46
P_219
N_140
N_213
N_125
H_554
P_50
H_484
H_549
P_24
N_134
N_560
N_289
P_276
H_542
P_209
N_224
P_252
N_448
H_460
P_429
P_506
H_11
N_196
H_207
H_34
H_523
N_497
H_495
H_126
P_179
H_191
P_76
H_323
P_392
P_412
H_412
H_502
H_363
N_283
P_508
P_70
N_413
N_0
P_89
P_323
N_476
P_447
H_595
H_346
H_287
H_311
N_528
N_440
P_197
N_447
P_399
P_292
P_282
P_6
N_109
H_442
N_548
H_488
P_488
P_418
H_474
N_182
P_119
P_17
P_258
P_141
N_95
H_52
N_290
H_97
N_261
H_118
H_434
N_203
N_199
N_367
N_147
P_211
H_255
N_255
P_298
N_572
P_1
N_392
N_274
H_203
P_118
H_1
H_185
P_62
H_168
H_44
N_192
P_77
N_244
N_273
H_272
H_283
N_150
H_534
H_112
P_546
N_284
N_351
N_532
P_571
P_494
P_120
H_62
H_300
P_388
P_308
N_24
H_459
H_447
P_330
H_477
P_168
P_479
N_187
N_534
N_165
P_218
H_111
P_115
